services:
  - type: cron
    name: executa-python-0830-a-2030
    env: python
    schedule: "30 11,13,15,17,19,21,23 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main

  - type: cron
    name: executa-python-2230
    env: python
    schedule: "30 1 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main
